version: "3.9"
services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./dynamic/:/etc/traefik/dynamic/:ro"
